LIST = 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99

include Makefile

### TestSSTableWriter
test100btargets  = $(addprefix test100b_, $(LIST))
test100b: $(test100btargets)

$(test100btargets): test100b_%:
	java -cp $(CLASSPATH) TestSSTableWriter in/data100B/data100B_$*.csv out/data100B/$*/test/test100b test100b



test10kbtargets  = $(addprefix test10kb_, $(LIST))
test10kb: $(test10kbtargets)

$(test10kbtargets): test10kb_%:
	java -cp $(CLASSPATH) TestSSTableWriter in/data10KB/data10KB_$*.csv out/data10KB/$*/test/test10kb test10kb



test1mbtargets  = $(addprefix test1mb_, $(LIST))
test1mb: $(test1mbtargets)

$(test1mbtargets): test1mb_%:
	java -cp $(CLASSPATH) TestSSTableWriter in/data1MB/data1MB_$*.csv out/data1MB/$*/test/test1mb test1mb


### TestSSTableWriter10
test10targets  = $(addprefix test10_, $(LIST))
test10: $(test10targets)

$(test10targets): test10_%:
	java -cp $(CLASSPATH) TestSSTableWriter10 in/data10/data10_$*.csv out/data10/$*/test/test10



### ExecAsync
exec100btargets  = $(addprefix exec100b_, $(LIST))
exec100b: $(exec100btargets)

$(exec100btargets): exec100b_%:
	java -cp $(CLASSPATH) ExecAsync in/data100B/data100B_$*.csv 10.109.180.2 test100b


exec10kbtargets  = $(addprefix exec10kb_, $(LIST))
exec10kb: $(exec10kbtargets)

$(exec10kbtargets): exec10kb_%:
	java -cp $(CLASSPATH) ExecAsync in/data10KB/data10KB_$*.csv 10.109.180.2 test10kb


exec1mbtargets  = $(addprefix exec1mb_, $(LIST))
exec1mb: $(exec1mbtargets)

$(exec1mbtargets): exec1mb_%:
	java -cp $(CLASSPATH) ExecAsync in/data1MB/data1MB_$*.csv 10.109.180.2 test1mb


### ExecAsync10
exec10targets  = $(addprefix exec10_, $(LIST))
exec10: $(exec10targets)

$(exec10targets): exec10_%:
	java -cp $(CLASSPATH) ExecAsync10 in/data10/data10_$*.csv 10.109.180.2



### sstableloader
sstable100btargets = $(addprefix sstable100b_, $(LIST))
sstable100b: $(sstable100btargets)

$(sstable100btargets): sstable100b_%:
	sstableloader -d 10.109.180.2 out/data100B/$*/test/test100b


sstable10kbtargets = $(addprefix sstable10kb_, $(LIST))
sstable10kb: $(sstable10kbtargets)

$(sstable10kbtargets): sstable10kb_%:
	sstableloader -d 10.109.180.2 out/data10KB/$*/test/test10kb


sstable1mbtargets = $(addprefix sstable1mb_, $(LIST))
sstable1mb: $(sstable1mbtargets)

$(sstable1mbtargets): sstable1mb_%:
	sstableloader -d 10.109.180.2 out/data1MB/$*/test/test1mb


sstable10targets = $(addprefix sstable10_, $(LIST))
sstable10: $(sstable10targets)

$(sstable10targets): sstable10_%:
	sstableloader -d 10.109.180.2 out/data10/$*/test/test10


### COPY FROM
copy100btargets = $(addprefix copy100b_, $(LIST))
copy100b: $(copy100btargets)

$(copy100btargets): copy100b_%:
	cqlsh -e "COPY test100b(pkey, ccol, data) FROM 'in/data100B/data100B_$*.csv'"

copy10kbtargets = $(addprefix copy10kb_, $(LIST))
copy10kb: $(copy10kbtargets)

$(copy10kbtargets): copy10kb_%:
	cqlsh -e "COPY test10kb(pkey, ccol, data) FROM 'in/data10KB/data10KB_$*.csv'"

copy1mbtargets = $(addprefix copy1mb_, $(LIST))
copy1mb: $(copy1mbtargets)

$(copy1mbtargets): copy1mb_%:
	cqlsh -e "COPY test1mb(pkey, ccol, data) FROM 'in/data1MB/data1MB_$*.csv'"

copy10targets = $(addprefix copy10_, $(LIST))
copy10: $(copy10targets)

$(copy10targets): copy10_%:
	cqlsh -e "COPY test10(pkey, ccol, c1, c2, c3, c4, c5, c6, c7, c8) FROM 'in/data10/data10_$*.csv'"


### TestSSTableWriterSplit
split100btargets  = $(addprefix split100b_, $(LIST))
split100b: $(split100btargets)

$(split100btargets): split100b_%:
	java -cp $(CLASSPATH) TestSSTableWriterSplit in/data100B/data100B_$*.csv out/data100B/$*/test/test100b test test100b 10.109.180.2



split10kbtargets  = $(addprefix split10kb_, $(LIST))
split10kb: $(split10kbtargets)

$(split10kbtargets): split10kb_%:
	java -cp $(CLASSPATH) TestSSTableWriterSplit in/data10KB/data10KB_$*.csv out/data10KB/$*/test/test10kb test test10kb 10.109.180.2



split1mbtargets  = $(addprefix split1mb_, $(LIST))
split1mb: $(split1mbtargets)

$(split1mbtargets): split1mb_%:
	java -cp $(CLASSPATH) TestSSTableWriterSplit in/data1MB/data1MB_$*.csv out/data1MB/$*/test/test1mb test test1mb 10.109.180.2


### TestSSTableWriterSplit10
split10targets  = $(addprefix split10_, $(LIST))
split10: $(split10targets)

$(split10targets): split10_%:
	java -cp $(CLASSPATH) TestSSTableWriterSplit10 in/data10/data10_$*.csv out/data10/$*/test/test10 10.109.180.2



### CPPExec
cpp100btargets  = $(addprefix cpp100b_, $(LIST))
cpp100b: $(cpp100btargets)

$(cpp100btargets): cpp100b_%:
	./cppexec in/data100B/data100B_$*.csv 10.109.180.2 test100b


cpp1kbtargets  = $(addprefix cpp1kb_, $(LIST))
cpp1kb: $(cpp1kbtargets)

$(cpp1kbtargets): cpp1kb_%:
	./cppexec in/data1KB/data1KB_$*.csv 10.109.180.2 test1kb


cpp10kbtargets  = $(addprefix cpp10kb_, $(LIST))
cpp10kb: $(cpp10kbtargets)

$(cpp10kbtargets): cpp10kb_%:
	./cppexec in/data10KB/data10KB_$*.csv 10.109.180.2 test10kb


cpp1mbtargets  = $(addprefix cpp1mb_, $(LIST))
cpp1mb: $(cpp1mbtargets)

$(cpp1mbtargets): cpp1mb_%:
	./cppexec in/data1MB/data1MB_$*.csv 10.109.180.2 test1mb


### CPPExec10
cpp10targets  = $(addprefix cpp10_, $(LIST))
cpp10: $(cpp10targets)

$(cpp10targets): cpp10_%:
	./cppexec10 in/data10/data10_$*.csv 10.109.180.2


